#!/usr/bin/env bash
# this script installs the nginx web server
# update package information
# install nginx
# check if nginx is installed
if [ $(dpkg-query -W -f='${Status}' nginx 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
	sudo apt-get update -y
	sudo apt-get install nginx -y
else
	echo "Nginx is already installed"
fi
# nginx should list on port 80
sudo ufw allow 'Nginx HTTP'
# create file to test nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
# update configuration file so /redirect_me is redirecting to another page

old_str="\tlocation / {\n"
new_str="\tlocation /redirect_me {\n\t\treturn 301 google.com;\n\t}\n\n\tlocation / {"
sudo sed -i "s|$old_str|$new_str|g" /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart

