#!/usr/bin/env bash
# this script installs the nginx web server
# update package information
# install nginx
# check if nginx is installed
string_exists() {
    awk -v str="$1" '$0 ~ str { found = 1; exit } END { exit !found }' "$2"
}

if [ "$(dpkg-query -W -f='${Status}' nginx 2>/dev/null | grep -c "ok installed")" -eq 0 ];
then
	sudo apt-get update -y
	sudo apt-get install nginx -y
# else
	# echo "Nginx is already installed"
fi
# nginx should list on port 80
sudo ufw allow 'Nginx HTTP'
# create file to test nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
# update configuration file so /redirect_me is redirecting to another page

my_setup="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	location / {
		try_files \$uri \$uri/ @404;
	}
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	error_page 404 /404.html;
	location = /404.html {
		root /var/www/html;
		internal;
	}
}" 
	echo -e "$my_setup" | sudo tee /etc/nginx/sites-available/default > /dev/null


# reload nginx
sudo service nginx restart

