#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

if ! command -v haproxy &>/dev/null;
then
	sudo apt-get install -y --no-install-recommends software-properties-common
	sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
	sudo apt-get update -y
	sudo apt-get install -y haproxy=2.8.\*

fi


sudo systemctl enable haproxy

echo "ENABLED=1" >> /etc/default/haproxy

my_config="defaults
	log	global
	mode http
	timeout connect 5s
	timeout client 50s
	timeout server 50s

frontend http_front
	bind *:80
	default_backend http_backends

backend http_backends
	balance roundrobin
	server 507480-web-01 54.144.238.161:80 check
	server 507480-web-02 100.25.154.52:80 check
	"

echo -e "$my_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null


if  ! sudo haproxy -c -f /etc/haproxy/haproxy.cfg > /dev/null ; then
    echo "Error: HAProxy configuration check failed. Please fix the configuration."
fi

sudo servic haproxy restart
