#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

if [ "$(dpkg-query -W -f='${Status}' haproxy 2>/dev/null | grep -c "ok installed")" -eq 0 ];
then
	sudo apt-get install --no-install-recommends software-properties-common
	sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
	sudo apt-get update -y
	sudo apt-get install -y haproxy=2.8.\*

fi

sudo systemctl stop haproxy
echo "ENABLED=1" | sudo -a tee /etc/default/haproxy

sudo systemctl start haproxy
sudo systemctl enable haproxy
my_config="global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log	global
	mode http
	option	httplog
	option	dontlognull
	timeout connect 5s
	timeout client 50s
	timeout server 50s

frontend http_front
	bind *:80
	default_backend http_backends

backend http_backends
	balance roundrobin
	server 507480-web-01 54.144.238.161:80 check
	server 507480-web-02 100.25.154.52:80 check
	"

echo -e "$my_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null


if  ! sudo haproxy -c -f /etc/haproxy/haproxy.cfg > /dev/null ; then
    echo "Error: HAProxy configuration check failed. Please fix the configuration."
fi

sudo systemctl restart haproxy
