#!/usr/bin/env bash
# displays a list of currently running processes
# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy
# alt:  ps -ejH u 
# alt:	ps axuf 
# alt:	ps -H aux
ps axuf
