#!/usr/bin/env bash
# infinite loop that doesnt die to SIGTERM

function infinite() {
	trap "trap_sigterm" SIGTERM
	while true
	do
		echo "To infinity and beyond"
		sleep 2

	done
}


function trap_sigterm()	{
	echo "I am invincible!!!"
}

infinite
