#!/usr/bin/env bash
#read the content of /etc/passwd and display:
#username, user id, and home dir path
#using while loop
file="/etc/passwd"
while  read -r line 
do
	echo  -n "$( echo "$line" | cut -d ':' -f 1)"
	echo -n ":"
	echo  -n "$( echo "$line" | cut -d ':' -f 3)"
	echo -n ":"
	echo  -n "$( echo "$line" | cut -d ':' -f 6)"
	echo
done < "$file"
