#!/usr/bin/env bash
# This script is looping from 1 to 20 using while loop and checking for condtions using case
i=1
while [ $i -le 20 ]
do	
	case $i in
		4)
			echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
		*)
			echo "$i";;

	esac
	((i++))
done
