#!/usr/bin/env bash
#this script gives you information about the school file
sch="school"
if [ -e "$sch" ]
then
	echo "school file exists"
	if [ ! -s "$sch" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$sch" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi

