#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements:
#	-	localhost resolves to 127.0.0.2
#	-	facebook.com resolves to 8.8.8.8
# Note: checker is running on Docker. Docker treats /etc/hosts differently.
# It overwrites it whenever it wants without any regard for your modifications.
# so we will make a copy of the /etc/hosts file:
cp /etc/hosts ~/hosts.new

# Use sed to modify /etc/hosts
# -i to edit file in place
# s/<regex>/<substitute>/ used to substitue the regular expression with another string
sed -i "s/^127.0.0.1[[:space:]]\+localhost/127.0.0.2 localhost/" ~/hosts.new

# Check if the line exists in hosts file
if ! grep -q "8.8.8.8[[:space:]]\+facebook.com" ~/hosts.new; then
    # Check if the domain exists with a different IP
    if grep -q "[[:space:]]\+facebook.com" ~/hosts.new; then
        # Replace the existing line with the desired IP
        sed -i "s/[[:space:]]\+facebook.com/8.8.8.8 facebook.com/"~/hosts.new 
    else
        # Add the line to hosts file
        echo "8.8.8.8 facebook.com" >>~/hosts.new 
    fi
fi

# finally copy hosts file back
cp -f ~/hosts.new /etc/hosts
