#!/usr/bin/env bash
#displays all active IPv4 IPs on the machine it’s executed on.
#using ifconfig and awk:
ifconfig | awk '/inet / {split($2, fields, " "); print fields[1]}'
#using ip, grep, awk, and cut
#	ip -4 addr show | grep inet | awk '{print $2}' | cut -d '/' -f 1 
