#!/usr/bin/env bash
# check if apache2 is installed
# if ! dpkg -s apache2 > /dev/null 2>&1
# then
# 	# install apache2
# 	sudo apt -y update > /dev/null 2>&1
# 	sudo apt -y install apache2 > /dev/null 2>&1
# fi
# sudo apt update -y
# sudo apt install apache2 -y
#docker exec -it 7fa7968d7810 service apache2 start
service apache2 start
