#!/usr/bin/env bash
# sudo apt update -y
# sudo apt install apache2 -y
# docker exec -it 7fa7968d7810 service apache2 start

if ! dpkg -s apache2 > /dev/null 2>&1
then
	# install apache2
	sudo apt -y update > /dev/null 2>&1
	sudo apt -y install apache2 > /dev/null 2>&1
fi

# install docker 
if ! dpkg -s docker > /dev/null 2>&1
then
	sudo apt -y update > /dev/null 2>&1
	sudo apt -y install docker > /dev/null 2>&1
fi

container_id=$(docker run -p 8080:80 -d -it holbertonschool/265-0) > /dev/null 2>&1

docker exec -it "$container_id" service apache2 start > /dev/null 2>&1
curl 0:8080
# ask to stop the container
# read -p "Press [Enter] key to stop the container..."
docker stop "$container_id" > /dev/null 2>&1
# sudo service apache2 start
