#!/usr/bin/env bash
sudo -u nginx chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx chmod u+r /etc/nginx/nginx.conf
sudo -u nginx sed -i 's/^#user .*$/user nginx nginx;/' /etc/nginx/nginx.conf
sudo -u nginx sed -i '/^.listen 80.*;/a	listen *:8080;'  /etc/nginx/sites-available/default
sudo -u nginx /usr/sbin/nginx -c /etc/nginx/nginx.conf
sudo -u nginx service nginx start
