#!/usr/bin/env bash
# This script will configure nginx to run as the nginx user
chown nginx:nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sudo -u nginx sed -i 's/^#user .*$/user nginx nginx;/' /etc/nginx/nginx.conf
sudo -u nginx sed -i '/^.listen 80.*;/a	listen *:8080;'  /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
