#!/usr/bin/env bash
# This script will configure nginx to run as the nginx user
sed -i 's/^#user .*$/user nginx;/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
