#!/usr/bin/env bash
# This script will configure nginx to run as the nginx user
sed -i 's/^#user .*$/user nginx;/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i '/^.listen 80.*;/a	listen *:8080;'  /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
